name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.0' # Change the version according to your project
          cache: 'npm' # Enable caching for node_modules

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Lint, Typecheck, and Tests
      - name: Run Lint, Typecheck, and Tests
        run: |
          npm run lint
          npm run typecheck
          npm run test
